# Generated by Django 2.0.1 on 2018-01-29 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20180129_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like',
            field=models.ManyToManyField(related_name='liked_comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
