# Generated by Django 2.0.1 on 2018-01-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
